// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v4.24.2
// source: api/proto/api.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	AntiBruteForceService_AddToBlackList_FullMethodName      = "/AntiBruteForceService/AddToBlackList"
	AntiBruteForceService_RemoveFromBlackList_FullMethodName = "/AntiBruteForceService/RemoveFromBlackList"
	AntiBruteForceService_AddToWhiteList_FullMethodName      = "/AntiBruteForceService/AddToWhiteList"
	AntiBruteForceService_RemoveFromWhiteList_FullMethodName = "/AntiBruteForceService/RemoveFromWhiteList"
	AntiBruteForceService_ClearLists_FullMethodName          = "/AntiBruteForceService/ClearLists"
	AntiBruteForceService_AuthCheck_FullMethodName           = "/AntiBruteForceService/AuthCheck"
	AntiBruteForceService_Reset_FullMethodName               = "/AntiBruteForceService/Reset"
)

// AntiBruteForceServiceClient is the client API for AntiBruteForceService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AntiBruteForceServiceClient interface {
	AddToBlackList(ctx context.Context, in *SubnetAddress, opts ...grpc.CallOption) (*emptypb.Empty, error)
	RemoveFromBlackList(ctx context.Context, in *SubnetAddress, opts ...grpc.CallOption) (*emptypb.Empty, error)
	AddToWhiteList(ctx context.Context, in *SubnetAddress, opts ...grpc.CallOption) (*emptypb.Empty, error)
	RemoveFromWhiteList(ctx context.Context, in *SubnetAddress, opts ...grpc.CallOption) (*emptypb.Empty, error)
	ClearLists(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*emptypb.Empty, error)
	AuthCheck(ctx context.Context, in *AuthCheckRequest, opts ...grpc.CallOption) (*AuthCheckResponse, error)
	Reset(ctx context.Context, in *AuthCheckRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type antiBruteForceServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAntiBruteForceServiceClient(cc grpc.ClientConnInterface) AntiBruteForceServiceClient {
	return &antiBruteForceServiceClient{cc}
}

func (c *antiBruteForceServiceClient) AddToBlackList(ctx context.Context, in *SubnetAddress, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, AntiBruteForceService_AddToBlackList_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *antiBruteForceServiceClient) RemoveFromBlackList(ctx context.Context, in *SubnetAddress, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, AntiBruteForceService_RemoveFromBlackList_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *antiBruteForceServiceClient) AddToWhiteList(ctx context.Context, in *SubnetAddress, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, AntiBruteForceService_AddToWhiteList_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *antiBruteForceServiceClient) RemoveFromWhiteList(ctx context.Context, in *SubnetAddress, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, AntiBruteForceService_RemoveFromWhiteList_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *antiBruteForceServiceClient) ClearLists(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, AntiBruteForceService_ClearLists_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *antiBruteForceServiceClient) AuthCheck(ctx context.Context, in *AuthCheckRequest, opts ...grpc.CallOption) (*AuthCheckResponse, error) {
	out := new(AuthCheckResponse)
	err := c.cc.Invoke(ctx, AntiBruteForceService_AuthCheck_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *antiBruteForceServiceClient) Reset(ctx context.Context, in *AuthCheckRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, AntiBruteForceService_Reset_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AntiBruteForceServiceServer is the server API for AntiBruteForceService service.
// All implementations must embed UnimplementedAntiBruteForceServiceServer
// for forward compatibility
type AntiBruteForceServiceServer interface {
	AddToBlackList(context.Context, *SubnetAddress) (*emptypb.Empty, error)
	RemoveFromBlackList(context.Context, *SubnetAddress) (*emptypb.Empty, error)
	AddToWhiteList(context.Context, *SubnetAddress) (*emptypb.Empty, error)
	RemoveFromWhiteList(context.Context, *SubnetAddress) (*emptypb.Empty, error)
	ClearLists(context.Context, *emptypb.Empty) (*emptypb.Empty, error)
	AuthCheck(context.Context, *AuthCheckRequest) (*AuthCheckResponse, error)
	Reset(context.Context, *AuthCheckRequest) (*emptypb.Empty, error)
	mustEmbedUnimplementedAntiBruteForceServiceServer()
}

// UnimplementedAntiBruteForceServiceServer must be embedded to have forward compatible implementations.
type UnimplementedAntiBruteForceServiceServer struct {
}

func (UnimplementedAntiBruteForceServiceServer) AddToBlackList(context.Context, *SubnetAddress) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddToBlackList not implemented")
}
func (UnimplementedAntiBruteForceServiceServer) RemoveFromBlackList(context.Context, *SubnetAddress) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RemoveFromBlackList not implemented")
}
func (UnimplementedAntiBruteForceServiceServer) AddToWhiteList(context.Context, *SubnetAddress) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddToWhiteList not implemented")
}
func (UnimplementedAntiBruteForceServiceServer) RemoveFromWhiteList(context.Context, *SubnetAddress) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RemoveFromWhiteList not implemented")
}
func (UnimplementedAntiBruteForceServiceServer) ClearLists(context.Context, *emptypb.Empty) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ClearLists not implemented")
}
func (UnimplementedAntiBruteForceServiceServer) AuthCheck(context.Context, *AuthCheckRequest) (*AuthCheckResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AuthCheck not implemented")
}
func (UnimplementedAntiBruteForceServiceServer) Reset(context.Context, *AuthCheckRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Reset not implemented")
}
func (UnimplementedAntiBruteForceServiceServer) mustEmbedUnimplementedAntiBruteForceServiceServer() {}

// UnsafeAntiBruteForceServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AntiBruteForceServiceServer will
// result in compilation errors.
type UnsafeAntiBruteForceServiceServer interface {
	mustEmbedUnimplementedAntiBruteForceServiceServer()
}

func RegisterAntiBruteForceServiceServer(s grpc.ServiceRegistrar, srv AntiBruteForceServiceServer) {
	s.RegisterService(&AntiBruteForceService_ServiceDesc, srv)
}

func _AntiBruteForceService_AddToBlackList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubnetAddress)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AntiBruteForceServiceServer).AddToBlackList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AntiBruteForceService_AddToBlackList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AntiBruteForceServiceServer).AddToBlackList(ctx, req.(*SubnetAddress))
	}
	return interceptor(ctx, in, info, handler)
}

func _AntiBruteForceService_RemoveFromBlackList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubnetAddress)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AntiBruteForceServiceServer).RemoveFromBlackList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AntiBruteForceService_RemoveFromBlackList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AntiBruteForceServiceServer).RemoveFromBlackList(ctx, req.(*SubnetAddress))
	}
	return interceptor(ctx, in, info, handler)
}

func _AntiBruteForceService_AddToWhiteList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubnetAddress)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AntiBruteForceServiceServer).AddToWhiteList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AntiBruteForceService_AddToWhiteList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AntiBruteForceServiceServer).AddToWhiteList(ctx, req.(*SubnetAddress))
	}
	return interceptor(ctx, in, info, handler)
}

func _AntiBruteForceService_RemoveFromWhiteList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubnetAddress)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AntiBruteForceServiceServer).RemoveFromWhiteList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AntiBruteForceService_RemoveFromWhiteList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AntiBruteForceServiceServer).RemoveFromWhiteList(ctx, req.(*SubnetAddress))
	}
	return interceptor(ctx, in, info, handler)
}

func _AntiBruteForceService_ClearLists_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AntiBruteForceServiceServer).ClearLists(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AntiBruteForceService_ClearLists_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AntiBruteForceServiceServer).ClearLists(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _AntiBruteForceService_AuthCheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AuthCheckRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AntiBruteForceServiceServer).AuthCheck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AntiBruteForceService_AuthCheck_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AntiBruteForceServiceServer).AuthCheck(ctx, req.(*AuthCheckRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AntiBruteForceService_Reset_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AuthCheckRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AntiBruteForceServiceServer).Reset(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AntiBruteForceService_Reset_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AntiBruteForceServiceServer).Reset(ctx, req.(*AuthCheckRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AntiBruteForceService_ServiceDesc is the grpc.ServiceDesc for AntiBruteForceService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AntiBruteForceService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "AntiBruteForceService",
	HandlerType: (*AntiBruteForceServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddToBlackList",
			Handler:    _AntiBruteForceService_AddToBlackList_Handler,
		},
		{
			MethodName: "RemoveFromBlackList",
			Handler:    _AntiBruteForceService_RemoveFromBlackList_Handler,
		},
		{
			MethodName: "AddToWhiteList",
			Handler:    _AntiBruteForceService_AddToWhiteList_Handler,
		},
		{
			MethodName: "RemoveFromWhiteList",
			Handler:    _AntiBruteForceService_RemoveFromWhiteList_Handler,
		},
		{
			MethodName: "ClearLists",
			Handler:    _AntiBruteForceService_ClearLists_Handler,
		},
		{
			MethodName: "AuthCheck",
			Handler:    _AntiBruteForceService_AuthCheck_Handler,
		},
		{
			MethodName: "Reset",
			Handler:    _AntiBruteForceService_Reset_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/proto/api.proto",
}
