name: CI/CD

on: push
jobs:
  check:
    runs-on: ubuntu-20.04
    steps:
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: ~1.20

      - name: Check out code
        uses: actions/checkout@v3

      - name: linter
        run: make lint

      - name: build
        run: make build

      - name: test
        run: make test

      - name: integration_test
        run: make integration-tests